service: myserverless-websocket
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  profile: cloud_user
  region: us-east-1
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"

custom:
  tableName: WebsocketUsers

functions:
  websocket-connect:
    handler: src/lambdas/websockets/connect.handler
    events:
      - websocket:
          route: $connect
  websocket-disconnect:
    handler: src/lambdas/websockets/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  websocket-default:
    handler: src/lambdas/websockets/default.handler
    events:
      - websocket:
          route: $default
  websocket-message:
    handler: src/lambdas/websockets/message.handler
    events:
      - websocket:
          route: message

resources:
  Resources:
    WeboscketUserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST